version: '3.7'

services:
    frontend-ionic:
        build: ./frontend-ionic
        image: dtmarangoni/udagram-dtm-frontend-ionic

    reverse-proxy:
        build: ./reverse-proxy
        image: dtmarangoni/udagram-dtm-reverse-proxy

    restapi-users:
        build: ./restapi-users
        image: dtmarangoni/udagram-dtm-restapi-users

    restapi-feed:
        build: ./restapi-feed
        image: dtmarangoni/udagram-dtm-restapi-feed

    img-filter:
        build: ./image-filter-microservice
        image: dtmarangoni/udagram-dtm-img-filter
