version: '3.7'

services:
    frontend-ionic:
        build: ./frontend-ionic
        image: dtmarangoni/udagram-dtm-frontend-ionic

    reverse-proxy:
        build: ./reverse-proxy
        image: dtmarangoni/udagram-dtm-reverse-proxy

    restapi-users:
        build: ./restapi-users
        image: dtmarangoni/udagram-dtm-restapi-users
        env_file: ./restapi-users/.environment_vars

    restapi-feed:
        build: ./restapi-feed
        image: dtmarangoni/udagram-dtm-restapi-feed
        env_file: ./restapi-feed/.environment_vars

    img-filter:
        build: ./image-filter-microservice
        image: dtmarangoni/udagram-dtm-img-filter
        env_file: ./image-filter-microservice/.environment_vars
