apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: img-filter-hpa
    labels:
        part-of: udagram-dtm-microservices
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: img-filter
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 50

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: restapi-users-hpa
    labels:
        part-of: udagram-dtm-microservices
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: restapi-users
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 50

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: restapi-feed-hpa
    labels:
        part-of: udagram-dtm-microservices
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: restapi-feed
    minReplicas: 2
    maxReplicas: 3
    targetCPUUtilizationPercentage: 50

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: reverse-proxy-hpa
    labels:
        part-of: udagram-dtm-microservices
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: reverse-proxy
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 50

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: frontend-ionic-hpa
    labels:
        part-of: udagram-dtm-microservices
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: frontend-ionic
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 50
